---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corosync-pvc
  namespace: proxmox-corosync
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
