---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: corosync-secrets-sync
  namespace: proxmox-corosync
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: corosync-secrets
  data:
  - secretKey: NEW_ROOT_PASSWORD
    remoteRef:
      key: <yourkeystore>/<yoursecret>
      property: proxmox-root-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secret
  namespace: proxmox-corosync
spec:
  secretStoreRef:
    name: vault-west
    kind: ClusterSecretStore
  target:
    name: harbor
    template:
      type: kubernetes.io/dockerconfigjson
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: <yourkeystore>/<yoursecret>
      property: dockerconfig.json        