---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-qdevice-lb
  namespace: proxmox-corosync
spec:
  type: LoadBalancer
  ports:
  - port: 22
    targetPort: 22
    name: ssh
  - port: 5403
    targetPort: 5403
    name: corosync
  selector:
    app: proxmox-qdevice